Repository cabralcaio/helpr-front-jfs5, pull requests merged in 2022-12, with the labels that each got.

#3 Exemplo de Pull Request
  src/app/views/clientes/new-cliente/new-cliente.component.css
Labels: enhancement

#4 funcionario component criado
  angular.json
  src/app/app-routing.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/funcionario.ts
  src/app/services/funcionario.service.ts
  src/app/views/funcionarios/funcionarios-routing.module.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.css
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
Labels: enhancement

#8 foi realizado o service de funcionario
  src/app/services/funcionario.service.ts
  src/app/views/funcionarios/funcionarios-routing.module.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.css
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.html
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.ts
Labels: enhancement

#9 Atualização do tema dark
  src/app/components/nav-bar/nav-bar.component.css
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.ts
  src/app/views/clientes/new-cliente/new-cliente.component.css
  src/custom-theme.scss
Labels: enhancement

#11 criado novo funcionario
  src/app/models/funcionario.ts
  src/app/services/funcionario.service.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.css
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.html
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.ts
Labels: enhancement

#15 Instalação do Firebase
  package-lock.json
  package.json
  src/app/app.module.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement

#16 criado cargo component
  src/app/app-routing.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/cargo.ts
  src/app/services/cargo.service.ts
  src/app/views/cargos/cargos-routing.module.ts
  src/app/views/cargos/cargos.module.ts
  src/app/views/cargos/cargos/cargos.component.css
  src/app/views/cargos/cargos/cargos.component.html
  src/app/views/cargos/cargos/cargos.component.ts
Labels: enhancement

#18 realizado service de cargo
  package-lock.json
  package.json
  src/app/models/funcionario.ts
  src/app/services/funcionario.service.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.html
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.ts
Labels: enhancement

#19 Adição do campo de upload da foto do perfil na página de adicionar fu…
  src/app/app.module.ts
  src/app/services/notification.service.ts
  src/app/services/upload.service.ts
  src/app/shared/material/material.module.ts
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.css
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.html
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.ts
Labels: enhancement

#21 Correção bug
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.html
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.ts
Labels: bug

#23 Listagem da foto dos funcionários
  src/app/pipes/avatar.pipe.ts
  src/app/services/funcionario.service.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.css
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.ts
  src/assets/images/avatar.png
Labels: enhancement

#25 Função de apagar adicionada a pagina funcionários
  src/app/services/funcionario.service.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
Labels: enhancement

#26 Criaçao do Carrossel home
  .vscode/settings.json
  angular.json
  package-lock.json
  package.json
  src/app/services/chamado.service.ts
  src/app/views/chamados/chamados-routing.module.ts
  src/app/views/chamados/chamados.module.ts
  src/app/views/chamados/chamados/chamados.component.html
  src/app/views/chamados/edit-chamado/edit-chamado.component.css
  src/app/views/chamados/edit-chamado/edit-chamado.component.html
  src/app/views/chamados/edit-chamado/edit-chamado.component.ts
  src/app/views/chamados/new-chamado/new-chamado.component.html
  src/app/views/home/home/home.component.html
  src/assets/4.png
  src/assets/5 .png
  src/assets/7.png
  src/index.html
Labels: enhancement

#28 edit Funcionario concluido
  src/app/models/funcionario.ts
  src/app/services/funcionario.service.ts
  src/app/views/funcionarios/edit-funcionario/edit-funcionario.component.css
  src/app/views/funcionarios/edit-funcionario/edit-funcionario.component.html
  src/app/views/funcionarios/edit-funcionario/edit-funcionario.component.ts
  src/app/views/funcionarios/funcionarios-routing.module.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.ts
Labels: enhancement

#30 Alteração da cor primaria do tema padrao
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/custom-theme.scss
Labels: enhancement

#31 página de visualização de futuro candidato
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/futuro-candidato.ts
  src/app/services/funcionario.service.ts
  src/app/services/futuro-candidato.service.ts
  src/app/views/clientes/clientes-routing.module.ts
  src/app/views/clientes/clientes.module.ts
  src/app/views/clientes/futuros-candidatos/futuros-candidatos.component.css
  src/app/views/clientes/futuros-candidatos/futuros-candidatos.component.html
  src/app/views/clientes/futuros-candidatos/futuros-candidatos.component.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
Labels: enhancement

#34 Exclusão de futuros candidatos concluido
  src/app/views/clientes/futuros-candidatos/futuros-candidatos.component.html
Labels: enhancement

#37 Função de deletar cargo concluida
  src/app/components/nav-bar/nav-bar.component.html
  src/app/services/cargo.service.ts
  src/app/views/cargos/cargos/cargos.component.html
  src/app/views/cargos/cargos/cargos.component.ts
Labels: enhancement

#39 Implementacao de detalhes funcionario
  src/app/app.module.ts
  src/app/components/components.module.ts
  src/app/components/details/details.component.css
  src/app/components/details/details.component.html
  src/app/components/details/details.component.ts
  src/app/shared/material/material.module.ts
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
Labels: enhancement

#41 Editar cargos concluido
  src/app/models/cargo.ts
  src/app/services/cargo.service.ts
  src/app/views/cargos/cargos-routing.module.ts
  src/app/views/cargos/cargos.module.ts
  src/app/views/cargos/edit-cargo/edit-cargo.component.css
  src/app/views/cargos/edit-cargo/edit-cargo.component.html
  src/app/views/cargos/edit-cargo/edit-cargo.component.ts
  src/app/views/funcionarios/edit-funcionario/edit-funcionario.component.ts
Labels: enhancement

#44 Redirecionamento e melhoria botão dark mode
  src/app/app-routing.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/shared/material/material.module.ts
Labels: enhancement

#42 Detalhes de chamado
  src/app/components/components.module.ts
  src/app/components/details-chamado/details-chamado.component.css
  src/app/components/details-chamado/details-chamado.component.html
  src/app/components/details-chamado/details-chamado.component.ts
  src/app/views/chamados/chamados.module.ts
  src/app/views/chamados/chamados/chamados.component.html
  src/app/views/chamados/chamados/chamados.component.ts
Labels: enhancement

#46 Correção para o dark mode ser salvo em todas as paginas
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.ts
Labels: enhancement

#51 titulos inclusos nas abas de cada rota
  src/Icon danav bar.png
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/components.module.ts
  src/app/components/details/details.component.html
  src/app/views/cargos/cargos-routing.module.ts
  src/app/views/chamados/chamados-routing.module.ts
  src/app/views/chamados/edit-chamado/edit-chamado.component.css
  src/app/views/chamados/edit-chamado/edit-chamado.component.html
  src/app/views/clientes/clientes-routing.module.ts
  src/app/views/funcionarios/funcionarios-routing.module.ts
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.css
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.html
  src/assets/images/Icon danav bar.png
  src/index.html
Labels: bug, enhancement

#54 cor de fundo login
  src/app/components/details/details.component.html
  src/app/views/login/login/login.component.css
  src/assets/2.png
  src/assets/Icon danav bar.png
  src/assets/quad1.png
  src/assets/quad2.png
Labels: enhancement

#56 Correção do link que busca imagem alternativa
  src/app/components/details/details.component.html
Labels: enhancement

#61 Correção do select sem fundo e do redirecionamento ao editar chamado
  src/app/app.component.ts
  src/app/components/nav-bar/nav-bar.component.ts
  src/app/views/chamados/edit-chamado/edit-chamado.component.ts
  src/app/views/funcionarios/new-funcionario/new-funcionario.component.css
Labels: bug

#62 Readme finalizado
  README.md
  src/app/views/funcionarios/funcionarios/funcionarios.component.css
  src/assets/images/mesdtn.png
  src/assets/images/projetohelpr.png
Labels: documentation
